version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: haliont/javascript-fastify-blog
    command: ['npm', 'test']
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
