version: '3.8'

services:
  app:
    build: .
    command: ['npm', 'run', 'dev']
    volumes:
      - ./app:/app
    ports:
      - 8080:8080

  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
